services:
  db:
    image: postgres:17
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      POSTGRES_DB: recipes
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    build: .
    command: npm run dev
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    environment:

      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
    volumes:
      - .:/app            # Map local project into container
      - /app/node_modules # Avoid overwriting node_modules from volume mapping
    depends_on:
      - db

volumes:
  postgres-data:

